apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: rad
webhooks:
  - name: rad.rad-webhook.svc.cluster.local
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1UQXlOekF6TXpFeU5sb1hEVEk1TVRBeU5EQXpNekV5Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTENGCmVCS1Z1REtTNUVMNnJWaUNzZGdTazZLWXJCZ3JLRWJVM1dxNmtrbW1DYUl6Ui9uTDBOSHlVM3B4RFUyMXVpZjIKYVIrSDJxNTRVK3hwRzhvVW1tY2NCTUtzWDRUMWFGdzY5VDF2MllHRWVpZEkrcTBWMGJBaTllWGhUVFZSaFNZUwp2dlczWDJZZDJIMU5JNkU4ZVpKeVZSVCtLb1pLaEx1QkR1QnNlM0xGYkhaNFZ2bFpOUGdnQ1FMeVZ2dSs4eWdtClB2T2FwczFseFdWdW14QTRDQ3kra1JMaFVwZk9jT3hienQyN0c4ZmRoY01wb1h0UDk2TnpNK2VRRVY1enhNWTQKZGhRRTF6ZXFFVXNFTS83Qis3SGFveElVQUJJZFNWa0c4WTVJMTkzNVZFOXhpSjJWdnBQa0lFdFc5SFhwY3F3egpSVEo0NTZPVVJOOVBZcWVZRUdVQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDSnFUN0w1YXpzVC9HcWJGSEt6OWZFazdweEYKdzUxcm5uRGVDOFJkcXZkYTJwV0t0ZzBRVk1jOFhFbXloeUl3c1prU1p2ZXd5ZEdaWXYxeEZQN3EwV2NuT1k2awpkQm0vbDdLUTB3Ukx5ZmszaVFkREVWTzgzOXhMR0h0em5HMGU3MHlYZ2tiYVhpaUFCNVFCOVlwbGttLzBYOUptCjE1YjdBbFQ3Y2czTDlpc1RYQnh0SDNqdDV0MzQ5Rk9HSkRXTUtVeDFHaTFHd25KZlk4VGFQaHJmejl1L2NabXQKYzk0TTdUZEgyNVh2d1NzdWdxb2lMQVQrQ2pDbU91Y2ZoV2hCbjUrb0NkUUNCUms3QlNjc3I2TGZ2OFM3R2xLRgpZamFwUUJLdDRwQm1xLzlGcnZlUENxQ0ovT3hscUdTUzZDM2FPa3Zhc09ZQmlQYzROdFNURzhlL3pwVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      service:
        name: rad
        namespace: rad-webhook
        path: "/mutate"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        rad: enabled
